import React from "react"

import Layout from "../components/layout"
import Seo from "../components/seo"
import './terms.scss'

const Terms = () => {

  return (
    <Layout>
      <Seo title="FAPP"/>
      <div className="gen-wrap terms">
        <h1>Terms of Service</h1>
        <h2>Terms of Service</h2>
        <p>FAPP-CB is a collection of digital artworks (so called Non-Fungible Tokens or “NFTs”) utilising blockchain technologies on the Ethereum network. This website is only an interface allowing participants to purchase these digital collectibles. Users are entirely responsible for the safety and management of their own private wallets and validating all transactions and contracts generated by this website before approval. Furthermore, as the FAPP-CB smart contract runs on the Ethereum network and is therefore bound by its immutability, there is no ability to undo, reverse, or restore any transactions, i.e., we are unable to offer refunds on any transactions.</p>
        <p>This website, our smart contract, and all connected services related to the FAPP-CB name are provided “as is” without any warranty or promise of availability of services of any kind. By using this website and minting the digital collectibles, you are accepting sole responsibility for any and all transactions involving FAPP-CB collectibles.</p>
        <h2>What you own</h2>
        <p>You will own the full commercial rights to your FAPP-CB and the underlying art so long as you continue to own and control the related NFT. Ownership of the NFT is mediated entirely by our smart contract. At no point can we seize, freeze, or otherwise modify the ownership of any NFT.</p>
        <p>You may assign some of these rights to other commercial projects, but any future transfer of your NFT will be subject to those rights that you have already assigned. You can put your FAPP-CB on clothing and merchandise, include them in video games and video projects, and generally do whatever you want with your FAPP-CB. You cannot use the name FAPP-CB on any commercial product, or use “FAPP” unless connected directly to the name or the “#” and the number of your FAPP-CB signifying the NFT you own. You agree not to use your FAPP-CB in any project or derivative work that involves hate speech, racism, pornography, or any other illegal content.</p>
        <h2>Limitations of liability</h2>
        <p>EXCEPT AS EXPRESSLY STATED IN THESE TERMS, THE FAPP TEAM DOES NOT MAKE ANY REPRESENTATIONS OR WARRANTIES AND EXPLICITLY DISCLAIMS ALL OTHER REPRESENTATIONS AND WARRANTIES, WHETHER EX-PRESS, IMPLIED, WRITTEN, ORAL OR STATUTORY, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND WARRANTIES OTHERWISE ARISING FROM A COURSE OF DEALING, COURSE OF PERFORMANCE OR USAGE OF TRADE.</p>
        <p>You agree to not hold the FAPP team responsibly for any losses you may incur as a consequence of minting your NFT, whether due to Internet connection issues, demand outstripping supply, or other unforeseen problems. These potential losses include any gas fees for failed transactions, any excessive gas fees charged due to website or smart contract bugs, and any loss of your NFT due to website or smart contract bugs.</p>
        <h2>No guarantee or promises of future services</h2>
        <p>The FAPP are fully committed to this project and hopes to continually develop the FAPP-CB story and grow the community. Our roadmap outlines future goals we hope to accomplish. While we fully intend to accomplish those goals, sometimes things happen and we cannot make any guarantees of the project selling nor can we guarantee any further developments. By minting a FAPP-CB, you agree that you are not relying on any future commitments by the FAPP team.</p>
        <p>Further, you agree to the following:</p>
        <ul>
          <li>A FAPP NFT token is not meant to be an investment. We make no claims or guarantees that your NFT will be worth anything. You understand that they have no inherent monetary value, and they should be treated as nothing more than a fun collectibles.</li>
          <li>You are entirely responsible for any tax liability which may arise from minting or reselling your FAPP-CB.</li>
          <li>You agree to waive any class action status, and any legal dispute around the FAPP project which you may choose to bring can only be done on an individual basis.</li>
          <li>The FAPP project is not targeted towards children. You agree that you are over the age of 18, or above the legal age of your jurisdiction, whichever is greater.</li>
          <li>You agree that for purposes of any legal dispute, you will be subject to the jurisdiction of Russia and that any legal proceeding will be brought in Russia.</li>
        </ul>
      </div>
    </Layout>
  )
}

export default Terms